# Generated by Django 5.2.9 on 2026-01-31 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_address_address_name_en_address_address_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='glovo_app.storemenu'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_category', to='glovo_app.category'),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_store', to='glovo_app.store'),
        ),
    ]
